name: encourage-developers

permissions:
  contents: read
  pull_requests: write

on:
  pull_request:
    types: [open]

jobs:
  encourage-developers:
  runs-on: ubuntu-latest
  steps:
    - name: Create Comments
      uses: actions/github-script@v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.issue.number;

          await github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'ã„ã„èª¿å­ï¼ğŸ‰å¼•ãç¶šãé–‹ç™ºã—ã¦ã„ã“ã†ï¼ğŸš€'
          })
      
